### ISSUE TITLE
Blip.TV is dead.

### ISSUE THREAD

**Issue by Cat5TV** [Viper007Bond/vipers-video-quicktags#6]
Maker Studios bought Blip.TV and shut it down in August 2015, yet currently Viper's Video Quicktags offers "Embed A Video From Blip" - this should be removed.

**Comment by Viper007Bond** [comment]
I've ceased development on this plugin but I'll be releasing a replacement for it soon: https://github.com/Viper007Bond/vipers-video-quicktags-migrator

That plugin will make all of the plugin's shortcodes be handled by the embed functionality that's built into WordPress, and for Blip.tv will display a message like `A video used to be embedded here but the service that it was hosted on has shut down.` in the post.
